### ISSUE TITLE
Docker container didn't start

### ISSUE THREAD

**Issue by kedramon** [WebsiteIntranetModel/wim#3]
After running 
`docker-compose up -d`
there is a error message 
`ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`

also 
`docker ps`
shows:
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

solution:
run in terminal
`eval "$(docker-machine env default)"`

**Comment by bramtenhove** [comment]
@kedramon I added this to my .bashrc:
`alias ds='docker-machine start;eval `docker-machine env`;docker start proxy;'`
